name: Build and push Docker images
on:
  push:
    branches: [ "main" ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker frontend image
      run: docker build ./frontend --file Dockerfile --tag frontend:$(date +%s)
  build-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker backend image
      run: docker build ./backend --file Dockerfile --tag backend:$(date +%s)
